# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-15 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('click_num', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '博客模块',
                'verbose_name_plural': '博客模块',
                'db_table': 'bloginfo',
            },
        ),
        migrations.DeleteModel(
            name='Grades',
        ),
    ]
